Issue 61: Enable Password Visibility
DSC-JSS-NOIDA/Plasma-Donor-App pull request #67
Opened 2020-10-10 19:58 UTC by ardlank

Fixes #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]

Checklist:

- [ ] I have checked for PMD and check-style issues 
- [ ] I have read the [Contribution & Best practices Guide](https://github.com/DSC-JSS-NOIDA/Plasma-Donor-App/blob/master/CONTRIBUTING.md) and my PR follows them.
- [ ] My branch is up-to-date with the Upstream development branch.

Changes: [Add here what changes were made in this issue and if possible provide links.]

Screenshots for the change:

2020-10-11 15:51 UTC, dheerajkotwani commented
@ardlank do provide the screenshots of the screen and do the same for signup screen as well.

2020-10-11 15:53 UTC, dheerajkotwani requested changes
@ardlank do provide the screenshots of the screen and do the same signup screen as well.

2020-10-11 22:15 UTC, ardlank commented
![Screenshot_1602454423](https://user-images.githubusercontent.com/23054357/95691542-64b60980-0be5-11eb-9405-44c6c457a0e3.png)
![Screenshot_1602454519](https://user-images.githubusercontent.com/23054357/95691543-654ea000-0be5-11eb-9631-34ae93282962.png)

@dheerajkotwani

2020-10-12 08:35 UTC, dheerajkotwani approved these changes

2020-10-12 08:36 UTC, merged